replicaCount: 1

image:
  repository: privatebin/nginx-fpm-alpine
  # tag: latest # defaults to Chart.appVersion
  pullPolicy: IfNotPresent
  # pullSecrets:
  #   - myRegistrKeySecretName

podAnnotations: {}
additionalLabels: {}

nameOverride: ""
fullnameOverride: ""
datapath: "/srv/data"

service:
  type: ClusterIP
  port: 80
  portName: http
  annotations: {}
  # loadBalancerSourceRanges: []

controller:
  # Valid values are "Deployment", "StatefulSet", and "Both"
  kind: Deployment
  pvc:
    requests: "1Gi"
    accessModes: "ReadWriteOnce"
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ## Please be aware that gp2 supports only RWO, check with
    ## this table:
    ## https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    ##
    # storageClass: "-"
  # For deployment controller, an emptyDir can be enable in the pod for writing data
  # with the following option
  emptyDir: false
securityContext:
  runAsUser: 65534
  runAsGroup: 82
  fsGroup: 82
  readOnlyRootFilesystem: true

ingress:
  className: nginx
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-zize: 64k
    nginx.ingress.kubernetes.io/auth-url: "https://privatebin.hetzner.dyvenia.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://privatebin.hetzner.dyvenia.com/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: privatebin.hetzner.dyvenia.com
      port: 80
      paths:
        - path: "/"
          pathType: Prefix

  tls: 
   - secretName: privatebin-ingress-tls-ca-issuer
     hosts:
       - privatebin.hetzner.dyvenia.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# nodeSelector: {}

# tolerations: []

# affinity: {}

# configs: {}
#   # conf.php: |-
#   #   ; see https://github.com/PrivateBin/PrivateBin/blob/master/cfg/conf.sample.php for config

## Enable RBAC
rbac:
  create: false
  serviceAccount:
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

# If true, create & use Pod Security Policy resources. Requires rbac.
podSecurityPolicy:
  enabled: false
  annotations: []
